apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJICAiZ2hjci5pbyI6IHsKCQkiYXV0aCI6ICJSR1Z1YVhNMk15MXpPbWRvY0Y5V04xSTBaRXBtWVZwcGFUSkVUbkZWUlhkMFpEVklaVTFWTXpoRFpWY3lTbTk0Ym5RPSIKCSAgfQoJfQogIH0=
type: kubernetes.io/dockerconfigjson
